use agent_kernel_core::{
    ActionId, AgentId, AgentImageDigest, AgentImageId, AgentImageKind, CapabilityId, CheckpointId,
    DeviceEventId, DeviceEventKind, DeviceEventPayload, DriverBindingId, DriverCommandId,
    DriverCommandKind, DriverCommandPayload, DriverCommandResult, DriverInvocationId, Event,
    EventKind, FaultId, FaultKind, FaultPolicyAction, FaultPolicyId, IntentId, IntentKind,
    MemoryCellId, MessageId, MessageKind, NamespaceEntryId, NamespaceKey, NamespaceObject,
    ObservationId, Operation, ResourceId, RuntimeAdmissionId, SignalKey, TaskId, TaskResult,
    VerificationRequirement, WaiterId, WaiterKind,
};

use super::all_operations;

pub fn complete_event() -> Event {
    Event {
        sequence: 1,
        agent: AgentId::new(2),
        kind: EventKind::DriverCommandCompleted,
        resource: Some(ResourceId::new(3)),
        capability: Some(CapabilityId::new(4)),
        source_capability: Some(CapabilityId::new(5)),
        intent: Some(IntentId::new(6)),
        intent_kind: Some(IntentKind::Rollback),
        action: Some(ActionId::new(7)),
        observation: Some(ObservationId::new(8)),
        message: Some(MessageId::new(9)),
        message_kind: Some(MessageKind::Fault),
        memory_cell: Some(MemoryCellId::new(10)),
        namespace_entry: Some(NamespaceEntryId::new(11)),
        namespace_key: Some(NamespaceKey::new(12)),
        namespace_object: Some(NamespaceObject::MemoryCell(MemoryCellId::new(13))),
        operation: Some(Operation::Rollback),
        operations: all_operations(),
        verification: VerificationRequirement::Required,
        checkpoint: Some(CheckpointId::new(14)),
        task: Some(TaskId::new(15)),
        runtime_admission: Some(RuntimeAdmissionId::new(16)),
        task_result: Some(TaskResult {
            code: 17,
            value: 18,
        }),
        task_ticks: Some(19),
        task_quantum: Some(20),
        fault: Some(FaultId::new(21)),
        fault_kind: Some(FaultKind::VerificationFault),
        fault_detail: Some(22),
        fault_policy: Some(FaultPolicyId::new(23)),
        fault_policy_action: Some(FaultPolicyAction::RecoverTask),
        waiter: Some(WaiterId::new(24)),
        waiter_kind: Some(WaiterKind::Mailbox),
        signal: Some(SignalKey::new(25)),
        target_agent: Some(AgentId::new(26)),
        driver_binding: Some(DriverBindingId::new(27)),
        device_event: Some(DeviceEventId::new(28)),
        device_event_kind: Some(DeviceEventKind::StateChanged),
        device_event_payload: Some(DeviceEventPayload {
            code: 29,
            value: 30,
        }),
        driver_command: Some(DriverCommandId::new(31)),
        driver_command_kind: Some(DriverCommandKind::Reset),
        driver_command_payload: Some(DriverCommandPayload {
            opcode: 32,
            value: 33,
        }),
        driver_command_result: Some(DriverCommandResult {
            code: 34,
            value: 35,
        }),
        driver_invocation: Some(DriverInvocationId::new(36)),
        driver_invocation_ticks: Some(37),
        driver_invocation_quantum: Some(38),
        agent_image: Some(AgentImageId::new(39)),
        agent_image_kind: Some(AgentImageKind::Driver),
        agent_image_digest: Some(AgentImageDigest::new([40; 32])),
        agent_image_abi_version: Some(41),
        agent_image_entry_version: Some(42),
    }
}
