//! Agent Image event recording helpers.
//!
//! This core-layer module keeps replay event construction separate from the
//! fixed-capacity Agent Image store. It records image provenance fields without
//! owning image lookup or launch validation.

use crate::{
    AgentId, AgentImageDigest, AgentImageId, AgentImageKind, CapabilityId, Event, EventKind,
    KernelCore, KernelError, Operation, OperationSet, ResourceId, VerificationRequirement,
};

impl<
        const AGENTS: usize,
        const RESOURCES: usize,
        const CAPS: usize,
        const EVENTS: usize,
        const ACTIONS: usize,
        const OBSERVATIONS: usize,
        const CHECKPOINTS: usize,
        const INTENTS: usize,
        const TASKS: usize,
        const RUN_QUEUE: usize,
        const MESSAGES: usize,
        const MEMORY_CELLS: usize,
        const NAMESPACE_ENTRIES: usize,
        const FAULTS: usize,
        const FAULT_HANDLERS: usize,
        const FAULT_POLICIES: usize,
        const WAITERS: usize,
        const AGENT_IMAGES: usize,
    >
    KernelCore<
        AGENTS,
        RESOURCES,
        CAPS,
        EVENTS,
        ACTIONS,
        OBSERVATIONS,
        CHECKPOINTS,
        INTENTS,
        TASKS,
        RUN_QUEUE,
        MESSAGES,
        MEMORY_CELLS,
        NAMESPACE_ENTRIES,
        FAULTS,
        FAULT_HANDLERS,
        FAULT_POLICIES,
        WAITERS,
        AGENT_IMAGES,
    >
{
    pub(crate) fn record_agent_image_registered_event(
        &mut self,
        owner: AgentId,
        capability: CapabilityId,
        resource: ResourceId,
        image: AgentImageId,
        kind: AgentImageKind,
        digest: AgentImageDigest,
        abi_version: u16,
        entry_version: u16,
    ) -> Result<Event, KernelError> {
        self.record(Event {
            sequence: 0,
            agent: owner,
            kind: EventKind::AgentImageRegistered,
            resource: Some(resource),
            capability: Some(capability),
            source_capability: None,
            intent: None,
            intent_kind: None,
            action: None,
            observation: None,
            message: None,
            memory_cell: None,
            namespace_entry: None,
            namespace_key: None,
            namespace_object: None,
            operation: Some(Operation::Act),
            operations: OperationSet::empty(),
            verification: VerificationRequirement::Optional,
            checkpoint: None,
            task: None,
            task_ticks: None,
            task_quantum: None,
            fault: None,
            fault_kind: None,
            fault_detail: None,
            fault_policy: None,
            fault_policy_action: None,
            waiter: None,
            signal: None,
            target_agent: Some(owner),
            agent_image: Some(image),
            agent_image_kind: Some(kind),
            agent_image_digest: Some(digest),
            agent_image_abi_version: Some(abi_version),
            agent_image_entry_version: Some(entry_version),
        })
    }

    pub(crate) fn record_agent_image_retired_event(
        &mut self,
        owner: AgentId,
        capability: CapabilityId,
        resource: ResourceId,
        image: AgentImageId,
        kind: AgentImageKind,
    ) -> Result<Event, KernelError> {
        self.record(Event {
            sequence: 0,
            agent: owner,
            kind: EventKind::AgentImageRetired,
            resource: Some(resource),
            capability: Some(capability),
            source_capability: None,
            intent: None,
            intent_kind: None,
            action: None,
            observation: None,
            message: None,
            memory_cell: None,
            namespace_entry: None,
            namespace_key: None,
            namespace_object: None,
            operation: Some(Operation::Rollback),
            operations: OperationSet::empty(),
            verification: VerificationRequirement::Optional,
            checkpoint: None,
            task: None,
            task_ticks: None,
            task_quantum: None,
            fault: None,
            fault_kind: None,
            fault_detail: None,
            fault_policy: None,
            fault_policy_action: None,
            waiter: None,
            signal: None,
            target_agent: Some(owner),
            agent_image: Some(image),
            agent_image_kind: Some(kind),
            agent_image_digest: None,
            agent_image_abi_version: None,
            agent_image_entry_version: None,
        })
    }
}
