//! Fixed-capacity Agent Kernel core state machine.
//!
//! Owns deterministic no_std stores for replay and supervisor inspection.

use crate::{
    ActionRecord, AgentEntryRecord, AgentExecutionContext, AgentImageRecord, AgentRecord,
    Capability, CheckpointRecord, DeviceEventRecord, DriverBindingRecord, Event,
    FaultHandlerRecord, FaultPolicyRecord, FaultRecord, Intent, MemoryCellRecord, MessageRecord,
    NamespaceEntryRecord, ObservationRecord, Resource, RunQueueEntry, Task, WaiterRecord,
};

#[derive(Debug)]
pub struct KernelCore<
    const AGENTS: usize,
    const RESOURCES: usize,
    const CAPS: usize,
    const EVENTS: usize,
    const ACTIONS: usize,
    const OBSERVATIONS: usize,
    const CHECKPOINTS: usize,
    const INTENTS: usize,
    const TASKS: usize,
    const RUN_QUEUE: usize,
    const MESSAGES: usize = 0,
    const MEMORY_CELLS: usize = 0,
    const NAMESPACE_ENTRIES: usize = 0,
    const FAULTS: usize = 0,
    const FAULT_HANDLERS: usize = 0,
    const FAULT_POLICIES: usize = 0,
    const WAITERS: usize = 0,
    const AGENT_IMAGES: usize = AGENTS,
    const DRIVER_BINDINGS: usize = 0,
    const DEVICE_EVENTS: usize = 0,
> {
    pub(crate) agents: [AgentRecord; AGENTS],
    pub(crate) execution_contexts: [AgentExecutionContext; AGENTS],
    pub(crate) agent_entries: [AgentEntryRecord; AGENTS],
    pub(crate) agent_images: [AgentImageRecord; AGENT_IMAGES],
    pub(crate) resources: [Resource; RESOURCES],
    pub(crate) capabilities: [Option<Capability>; CAPS],
    pub(crate) intents: [Intent; INTENTS],
    pub(crate) events: [Event; EVENTS],
    pub(crate) actions: [ActionRecord; ACTIONS],
    pub(crate) observations: [ObservationRecord; OBSERVATIONS],
    pub(crate) checkpoints: [CheckpointRecord; CHECKPOINTS],
    pub(crate) tasks: [Task; TASKS],
    pub(crate) run_queue: [RunQueueEntry; RUN_QUEUE],
    pub(crate) messages: [MessageRecord; MESSAGES],
    pub(crate) memory_cells: [MemoryCellRecord; MEMORY_CELLS],
    pub(crate) namespace_entries: [NamespaceEntryRecord; NAMESPACE_ENTRIES],
    pub(crate) faults: [FaultRecord; FAULTS],
    pub(crate) fault_handlers: [FaultHandlerRecord; FAULT_HANDLERS],
    pub(crate) fault_policies: [FaultPolicyRecord; FAULT_POLICIES],
    pub(crate) waiters: [WaiterRecord; WAITERS],
    pub(crate) driver_bindings: [DriverBindingRecord; DRIVER_BINDINGS],
    pub(crate) device_events: [DeviceEventRecord; DEVICE_EVENTS],
    pub(crate) agent_len: usize,
    pub(crate) agent_entry_len: usize,
    pub(crate) agent_image_len: usize,
    pub(crate) resource_len: usize,
    pub(crate) event_len: usize,
    pub(crate) action_len: usize,
    pub(crate) observation_len: usize,
    pub(crate) checkpoint_len: usize,
    pub(crate) intent_len: usize,
    pub(crate) task_len: usize,
    pub(crate) run_queue_len: usize,
    pub(crate) message_len: usize,
    pub(crate) memory_cell_len: usize,
    pub(crate) namespace_entry_len: usize,
    pub(crate) fault_len: usize,
    pub(crate) fault_handler_len: usize,
    pub(crate) fault_policy_len: usize,
    pub(crate) waiter_len: usize,
    pub(crate) driver_binding_len: usize,
    pub(crate) device_event_len: usize,
    pub(crate) next_resource: u64,
    pub(crate) next_capability: u64,
    pub(crate) next_observation: u64,
    pub(crate) next_intent: u64,
    pub(crate) next_task: u64,
    pub(crate) next_message: u64,
    pub(crate) next_memory_cell: u64,
    pub(crate) next_namespace_entry: u64,
    pub(crate) next_fault: u64,
    pub(crate) next_fault_handler: u64,
    pub(crate) next_fault_policy: u64,
    pub(crate) next_waiter: u64,
    pub(crate) next_agent_image: u64,
    pub(crate) next_driver_binding: u64,
    pub(crate) next_device_event: u64,
    pub(crate) next_sequence: u64,
}

impl<
        const AGENTS: usize,
        const RESOURCES: usize,
        const CAPS: usize,
        const EVENTS: usize,
        const ACTIONS: usize,
        const OBSERVATIONS: usize,
        const CHECKPOINTS: usize,
        const INTENTS: usize,
        const TASKS: usize,
        const RUN_QUEUE: usize,
        const MESSAGES: usize,
        const MEMORY_CELLS: usize,
        const NAMESPACE_ENTRIES: usize,
        const FAULTS: usize,
        const FAULT_HANDLERS: usize,
        const FAULT_POLICIES: usize,
        const WAITERS: usize,
        const AGENT_IMAGES: usize,
        const DRIVER_BINDINGS: usize,
        const DEVICE_EVENTS: usize,
    >
    KernelCore<
        AGENTS,
        RESOURCES,
        CAPS,
        EVENTS,
        ACTIONS,
        OBSERVATIONS,
        CHECKPOINTS,
        INTENTS,
        TASKS,
        RUN_QUEUE,
        MESSAGES,
        MEMORY_CELLS,
        NAMESPACE_ENTRIES,
        FAULTS,
        FAULT_HANDLERS,
        FAULT_POLICIES,
        WAITERS,
        AGENT_IMAGES,
        DRIVER_BINDINGS,
        DEVICE_EVENTS,
    >
{
    pub const fn new() -> Self {
        Self {
            agents: [AgentRecord::empty(); AGENTS],
            execution_contexts: [AgentExecutionContext::empty(); AGENTS],
            agent_entries: [AgentEntryRecord::empty(); AGENTS],
            agent_images: [AgentImageRecord::empty(); AGENT_IMAGES],
            resources: [Resource::empty(); RESOURCES],
            capabilities: [None; CAPS],
            intents: [Intent::empty(); INTENTS],
            events: [Event::empty(); EVENTS],
            actions: [ActionRecord::empty(); ACTIONS],
            observations: [ObservationRecord::empty(); OBSERVATIONS],
            checkpoints: [CheckpointRecord::empty(); CHECKPOINTS],
            tasks: [Task::empty(); TASKS],
            run_queue: [RunQueueEntry::empty(); RUN_QUEUE],
            messages: [MessageRecord::empty(); MESSAGES],
            memory_cells: [MemoryCellRecord::empty(); MEMORY_CELLS],
            namespace_entries: [NamespaceEntryRecord::empty(); NAMESPACE_ENTRIES],
            faults: [FaultRecord::empty(); FAULTS],
            fault_handlers: [FaultHandlerRecord::empty(); FAULT_HANDLERS],
            fault_policies: [FaultPolicyRecord::empty(); FAULT_POLICIES],
            waiters: [WaiterRecord::empty(); WAITERS],
            driver_bindings: [DriverBindingRecord::empty(); DRIVER_BINDINGS],
            device_events: [DeviceEventRecord::empty(); DEVICE_EVENTS],
            agent_len: 0,
            agent_entry_len: 0,
            agent_image_len: 0,
            resource_len: 0,
            event_len: 0,
            action_len: 0,
            observation_len: 0,
            checkpoint_len: 0,
            intent_len: 0,
            task_len: 0,
            run_queue_len: 0,
            message_len: 0,
            memory_cell_len: 0,
            namespace_entry_len: 0,
            fault_len: 0,
            fault_handler_len: 0,
            fault_policy_len: 0,
            waiter_len: 0,
            driver_binding_len: 0,
            device_event_len: 0,
            next_resource: 1,
            next_capability: 1,
            next_observation: 1,
            next_intent: 1,
            next_task: 1,
            next_message: 1,
            next_memory_cell: 1,
            next_namespace_entry: 1,
            next_fault: 1,
            next_fault_handler: 1,
            next_fault_policy: 1,
            next_waiter: 1,
            next_agent_image: 1,
            next_driver_binding: 1,
            next_device_event: 1,
            next_sequence: 1,
        }
    }
}

impl<
        const AGENTS: usize,
        const RESOURCES: usize,
        const CAPS: usize,
        const EVENTS: usize,
        const ACTIONS: usize,
        const OBSERVATIONS: usize,
        const CHECKPOINTS: usize,
        const INTENTS: usize,
        const TASKS: usize,
        const RUN_QUEUE: usize,
        const MESSAGES: usize,
        const MEMORY_CELLS: usize,
        const NAMESPACE_ENTRIES: usize,
        const FAULTS: usize,
        const FAULT_HANDLERS: usize,
        const FAULT_POLICIES: usize,
        const WAITERS: usize,
        const AGENT_IMAGES: usize,
        const DRIVER_BINDINGS: usize,
        const DEVICE_EVENTS: usize,
    > Default
    for KernelCore<
        AGENTS,
        RESOURCES,
        CAPS,
        EVENTS,
        ACTIONS,
        OBSERVATIONS,
        CHECKPOINTS,
        INTENTS,
        TASKS,
        RUN_QUEUE,
        MESSAGES,
        MEMORY_CELLS,
        NAMESPACE_ENTRIES,
        FAULTS,
        FAULT_HANDLERS,
        FAULT_POLICIES,
        WAITERS,
        AGENT_IMAGES,
        DRIVER_BINDINGS,
        DEVICE_EVENTS,
    >
{
    fn default() -> Self {
        Self::new()
    }
}
