//! Replay event construction for Driver Invocation runtime transitions.
//!
//! This core-layer module maps fixed-width invocation records into the shared
//! event schema. Runtime modules validate and mutate state; this module only
//! records their already-authorized transition data without allocation or I/O.

use crate::{
    AgentId, CapabilityId, DriverInvocationId, Event, EventKind, KernelCore, KernelError,
    Operation, OperationSet, VerificationRequirement,
};

impl<
        const AGENTS: usize,
        const RESOURCES: usize,
        const CAPS: usize,
        const EVENTS: usize,
        const ACTIONS: usize,
        const OBSERVATIONS: usize,
        const CHECKPOINTS: usize,
        const INTENTS: usize,
        const TASKS: usize,
        const RUN_QUEUE: usize,
        const MESSAGES: usize,
        const MEMORY_CELLS: usize,
        const NAMESPACE_ENTRIES: usize,
        const FAULTS: usize,
        const FAULT_HANDLERS: usize,
        const FAULT_POLICIES: usize,
        const WAITERS: usize,
        const AGENT_IMAGES: usize,
        const DRIVER_BINDINGS: usize,
        const DEVICE_EVENTS: usize,
        const DRIVER_COMMANDS: usize,
        const DRIVER_INVOCATIONS: usize,
        const RUNTIME_ADMISSIONS: usize,
    >
    KernelCore<
        AGENTS,
        RESOURCES,
        CAPS,
        EVENTS,
        ACTIONS,
        OBSERVATIONS,
        CHECKPOINTS,
        INTENTS,
        TASKS,
        RUN_QUEUE,
        MESSAGES,
        MEMORY_CELLS,
        NAMESPACE_ENTRIES,
        FAULTS,
        FAULT_HANDLERS,
        FAULT_POLICIES,
        WAITERS,
        AGENT_IMAGES,
        DRIVER_BINDINGS,
        DEVICE_EVENTS,
        DRIVER_COMMANDS,
        DRIVER_INVOCATIONS,
        RUNTIME_ADMISSIONS,
    >
{
    #[allow(clippy::too_many_arguments)]
    pub(crate) fn record_driver_invocation_event(
        &mut self,
        kind: EventKind,
        driver: AgentId,
        capability: Option<CapabilityId>,
        invocation: DriverInvocationId,
        operation: Operation,
        ticks: Option<u64>,
        quantum: Option<u64>,
    ) -> Result<Event, KernelError> {
        let record = self.find_driver_invocation(invocation)?;
        self.record(Event {
            sequence: 0,
            agent: driver,
            kind,
            resource: Some(record.resource),
            capability,
            source_capability: None,
            intent: None,
            intent_kind: None,
            action: None,
            observation: None,
            message: None,
            message_kind: None,
            memory_cell: None,
            namespace_entry: None,
            namespace_key: None,
            namespace_object: None,
            operation: Some(operation),
            operations: OperationSet::empty(),
            verification: VerificationRequirement::Optional,
            checkpoint: None,
            task: None,
            runtime_admission: None,
            task_result: None,
            task_ticks: None,
            task_quantum: None,
            fault: None,
            fault_kind: None,
            fault_detail: None,
            fault_policy: None,
            fault_policy_action: None,
            waiter: None,
            waiter_kind: None,
            signal: None,
            target_agent: None,
            driver_binding: Some(record.binding),
            device_event: Some(record.event),
            device_event_kind: None,
            device_event_payload: None,
            driver_command: None,
            driver_command_kind: None,
            driver_command_payload: None,
            driver_command_result: None,
            driver_invocation: Some(invocation),
            driver_invocation_ticks: ticks,
            driver_invocation_quantum: quantum,
            agent_image: None,
            agent_image_kind: None,
            agent_image_digest: None,
            agent_image_abi_version: None,
            agent_image_entry_version: None,
            agent_image_signer: None,
        })
    }
}
