//! Replay event construction for native driver command transitions.
//!
//! This core-layer module maps already-authorized command state changes into the
//! shared event schema. Submission and runtime transition modules own validation
//! and mutation; this module performs no hardware I/O or allocation.

use crate::{
    AgentId, CapabilityId, DeviceEventId, DriverBindingId, DriverCommandId, DriverCommandKind,
    DriverCommandPayload, DriverCommandResult, DriverInvocationId, Event, EventKind, KernelCore,
    KernelError, Operation, OperationSet, ResourceId, VerificationRequirement,
};

impl<
        const AGENTS: usize,
        const RESOURCES: usize,
        const CAPS: usize,
        const EVENTS: usize,
        const ACTIONS: usize,
        const OBSERVATIONS: usize,
        const CHECKPOINTS: usize,
        const INTENTS: usize,
        const TASKS: usize,
        const RUN_QUEUE: usize,
        const MESSAGES: usize,
        const MEMORY_CELLS: usize,
        const NAMESPACE_ENTRIES: usize,
        const FAULTS: usize,
        const FAULT_HANDLERS: usize,
        const FAULT_POLICIES: usize,
        const WAITERS: usize,
        const AGENT_IMAGES: usize,
        const DRIVER_BINDINGS: usize,
        const DEVICE_EVENTS: usize,
        const DRIVER_COMMANDS: usize,
        const DRIVER_INVOCATIONS: usize,
    >
    KernelCore<
        AGENTS,
        RESOURCES,
        CAPS,
        EVENTS,
        ACTIONS,
        OBSERVATIONS,
        CHECKPOINTS,
        INTENTS,
        TASKS,
        RUN_QUEUE,
        MESSAGES,
        MEMORY_CELLS,
        NAMESPACE_ENTRIES,
        FAULTS,
        FAULT_HANDLERS,
        FAULT_POLICIES,
        WAITERS,
        AGENT_IMAGES,
        DRIVER_BINDINGS,
        DEVICE_EVENTS,
        DRIVER_COMMANDS,
        DRIVER_INVOCATIONS,
    >
{
    #[allow(clippy::too_many_arguments)]
    pub(crate) fn record_driver_command_event(
        &mut self,
        event_kind: EventKind,
        driver: AgentId,
        capability: CapabilityId,
        binding: DriverBindingId,
        command: DriverCommandId,
        resource: ResourceId,
        cause: Option<DeviceEventId>,
        invocation: Option<DriverInvocationId>,
        command_kind: DriverCommandKind,
        payload: DriverCommandPayload,
        result: Option<DriverCommandResult>,
    ) -> Result<Event, KernelError> {
        self.record(Event {
            sequence: 0,
            agent: driver,
            kind: event_kind,
            resource: Some(resource),
            capability: Some(capability),
            source_capability: None,
            intent: None,
            intent_kind: None,
            action: None,
            observation: None,
            message: None,
            memory_cell: None,
            namespace_entry: None,
            namespace_key: None,
            namespace_object: None,
            operation: Some(Operation::Act),
            operations: OperationSet::empty(),
            verification: VerificationRequirement::Optional,
            checkpoint: None,
            task: None,
            task_result: None,
            task_ticks: None,
            task_quantum: None,
            fault: None,
            fault_kind: None,
            fault_detail: None,
            fault_policy: None,
            fault_policy_action: None,
            waiter: None,
            signal: None,
            target_agent: None,
            driver_binding: Some(binding),
            device_event: cause,
            device_event_kind: None,
            device_event_payload: None,
            driver_command: Some(command),
            driver_command_kind: Some(command_kind),
            driver_command_payload: Some(payload),
            driver_command_result: result,
            driver_invocation: invocation,
            driver_invocation_ticks: None,
            driver_invocation_quantum: None,
            agent_image: None,
            agent_image_kind: None,
            agent_image_digest: None,
            agent_image_abi_version: None,
            agent_image_entry_version: None,
        })
    }
}
