//! Explicit Agent Kernel error values.
//!
//! This module owns deterministic errors for capacity, lookup, authorization,
//! and revocation failures. Normal kernel failures must return these errors
//! instead of panicking.

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum KernelError {
    AgentStoreFull,
    ResourceStoreFull,
    CapabilityStoreFull,
    EventLogFull,
    ActionStoreFull,
    ObservationStoreFull,
    CheckpointStoreFull,
    FaultStoreFull,
    FaultHandlerStoreFull,
    FaultPolicyStoreFull,
    WaiterStoreFull,
    MessageStoreFull,
    MemoryCellStoreFull,
    NamespaceEntryStoreFull,
    AgentEntryStoreFull,
    AgentAlreadyExists,
    AgentNotFound,
    AgentEntryNotFound,
    AgentAlreadyLaunched,
    AgentSuspended,
    AgentRetired,
    AgentStatusMismatch,
    ResourceNotFound,
    ResourceRetired,
    CapabilityNotFound,
    ActionAlreadyExists,
    ActionNotFound,
    ActionResourceMismatch,
    ActionStatusMismatch,
    CheckpointAlreadyExists,
    CheckpointNotFound,
    CheckpointResourceMismatch,
    CheckpointStatusMismatch,
    CapabilityRevoked,
    CapabilityScopeMismatch,
    AgentMismatch,
    ResourceMismatch,
    OperationDenied,
    IntentStoreFull,
    IntentNotFound,
    IntentAgentMismatch,
    IntentKindMismatch,
    IntentStatusMismatch,
    TaskStoreFull,
    TaskNotFound,
    TaskAgentMismatch,
    TaskStatusMismatch,
    TaskQuantumInvalid,
    RunQueueFull,
    RunQueueEmpty,
    TaskNotRunnable,
    TaskAlreadyQueued,
    ExecutionContextBusy,
    FaultHandlerAlreadyExists,
    FaultHandlerNotFound,
    FaultPolicyAlreadyExists,
    FaultPolicyNotFound,
    MessageNotFound,
    MessageAgentMismatch,
    MessageStatusMismatch,
    MailboxEmpty,
    MemoryCellNotFound,
    NamespaceEntryNotFound,
    NamespaceEntryAlreadyExists,
    ResourceKindMismatch,
}
