//! Explicit Agent Kernel error values.
//!
//! This module owns deterministic errors for capacity, lookup, authorization,
//! and revocation failures. Normal kernel failures must return these errors
//! instead of panicking.

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum KernelError {
    AgentStoreFull,
    ResourceStoreFull,
    CapabilityStoreFull,
    EventLogFull,
    ActionStoreFull,
    ObservationStoreFull,
    CheckpointStoreFull,
    AgentAlreadyExists,
    AgentNotFound,
    AgentSuspended,
    AgentRetired,
    AgentStatusMismatch,
    ResourceNotFound,
    CapabilityNotFound,
    ActionAlreadyExists,
    ActionNotFound,
    ActionResourceMismatch,
    ActionStatusMismatch,
    CheckpointAlreadyExists,
    CheckpointNotFound,
    CheckpointResourceMismatch,
    CheckpointStatusMismatch,
    CapabilityRevoked,
    CapabilityScopeMismatch,
    AgentMismatch,
    ResourceMismatch,
    OperationDenied,
    IntentStoreFull,
    IntentNotFound,
    IntentAgentMismatch,
    IntentStatusMismatch,
    TaskStoreFull,
    TaskNotFound,
    TaskAgentMismatch,
    TaskStatusMismatch,
    RunQueueFull,
    RunQueueEmpty,
    TaskNotRunnable,
    TaskAlreadyQueued,
}
