//! Kernel event records.
//!
//! This module owns the replayable event shape for observations, actions,
//! capability lifecycle changes, verification requests, checkpoints, rollback
//! requests, delegation, and scheduler decisions.

use crate::{
    ActionId, AgentId, AgentImageDigest, AgentImageId, AgentImageKind, CapabilityId, CheckpointId,
    DeviceEventId, DeviceEventKind, DeviceEventPayload, DriverBindingId, FaultId, FaultKind,
    FaultPolicyAction, FaultPolicyId, IntentId, IntentKind, MemoryCellId, MessageId,
    NamespaceEntryId, NamespaceKey, NamespaceObject, ObservationId, Operation, OperationSet,
    ResourceId, SignalKey, TaskId, VerificationRequirement, WaiterId,
};

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum EventKind {
    AgentRegistered,
    AgentImageRegistered,
    AgentImageVerified,
    AgentImageRetired,
    AgentLaunched,
    AgentSuspended,
    AgentResumed,
    AgentRetired,
    DriverBound,
    DeviceEventRaised,
    DeviceEventDelivered,
    DeviceEventAcknowledged,
    ResourceCreated,
    ResourceRetired,
    CapabilityGranted,
    CapabilityDerived,
    CapabilityRevoked,
    IntentDeclared,
    IntentBound,
    IntentFulfilled,
    IntentCancelled,
    Observation,
    ActionExecuted,
    VerificationRequested,
    CheckpointCreated,
    RollbackRequested,
    DelegationRequested,
    TaskCreated,
    TaskAccepted,
    TaskCompleted,
    TaskVerified,
    TaskCancelled,
    TaskQueued,
    TaskDispatched,
    TaskYielded,
    TaskTicked,
    TaskQuantumExpired,
    TaskWaiting,
    TaskWoken,
    TaskFaulted,
    TaskFaultRecovered,
    SignalEmitted,
    FaultHandlerInstalled,
    FaultRouted,
    FaultPolicyInstalled,
    FaultPolicyApplied,
    MessageSent,
    MessageReceived,
    MessageAcknowledged,
    MemoryCellCreated,
    MemoryCellRecalled,
    MemoryCellRemembered,
    NamespaceEntryBound,
    NamespaceEntryResolved,
    NamespaceEntryRebound,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct Event {
    pub sequence: u64,
    pub agent: AgentId,
    pub kind: EventKind,
    pub resource: Option<ResourceId>,
    pub capability: Option<CapabilityId>,
    pub source_capability: Option<CapabilityId>,
    pub intent: Option<IntentId>,
    pub intent_kind: Option<IntentKind>,
    pub action: Option<ActionId>,
    pub observation: Option<ObservationId>,
    pub message: Option<MessageId>,
    pub memory_cell: Option<MemoryCellId>,
    pub namespace_entry: Option<NamespaceEntryId>,
    pub namespace_key: Option<NamespaceKey>,
    pub namespace_object: Option<NamespaceObject>,
    pub operation: Option<Operation>,
    pub operations: OperationSet,
    pub verification: VerificationRequirement,
    pub checkpoint: Option<CheckpointId>,
    pub task: Option<TaskId>,
    pub task_ticks: Option<u64>,
    pub task_quantum: Option<u64>,
    pub fault: Option<FaultId>,
    pub fault_kind: Option<FaultKind>,
    pub fault_detail: Option<u64>,
    pub fault_policy: Option<FaultPolicyId>,
    pub fault_policy_action: Option<FaultPolicyAction>,
    pub waiter: Option<WaiterId>,
    pub signal: Option<SignalKey>,
    pub target_agent: Option<AgentId>,
    pub driver_binding: Option<DriverBindingId>,
    pub device_event: Option<DeviceEventId>,
    pub device_event_kind: Option<DeviceEventKind>,
    pub device_event_payload: Option<DeviceEventPayload>,
    pub agent_image: Option<AgentImageId>,
    pub agent_image_kind: Option<AgentImageKind>,
    pub agent_image_digest: Option<AgentImageDigest>,
    pub agent_image_abi_version: Option<u16>,
    pub agent_image_entry_version: Option<u16>,
}

impl Event {
    pub(crate) const fn empty() -> Self {
        Self {
            sequence: 0,
            agent: AgentId::new(0),
            kind: EventKind::Observation,
            resource: None,
            capability: None,
            source_capability: None,
            intent: None,
            intent_kind: None,
            action: None,
            observation: None,
            message: None,
            memory_cell: None,
            namespace_entry: None,
            namespace_key: None,
            namespace_object: None,
            operation: None,
            operations: OperationSet::empty(),
            verification: VerificationRequirement::Optional,
            checkpoint: None,
            task: None,
            task_ticks: None,
            task_quantum: None,
            fault: None,
            fault_kind: None,
            fault_detail: None,
            fault_policy: None,
            fault_policy_action: None,
            waiter: None,
            signal: None,
            target_agent: None,
            driver_binding: None,
            device_event: None,
            device_event_kind: None,
            device_event_payload: None,
            agent_image: None,
            agent_image_kind: None,
            agent_image_digest: None,
            agent_image_abi_version: None,
            agent_image_entry_version: None,
        }
    }
}
