//! Wait signal event builders.
//!
//! This module belongs to `agent-kernel-core`. It keeps wait, signal, and wake
//! event construction separate from signal state transitions while preserving
//! fixed-field no_std event records.

use crate::{
    AgentId, CapabilityId, Event, EventKind, KernelCore, KernelError, OperationSet, ResourceId,
    SignalKey, TaskId, VerificationRequirement, WaiterId,
};

impl<
        const AGENTS: usize,
        const RESOURCES: usize,
        const CAPS: usize,
        const EVENTS: usize,
        const ACTIONS: usize,
        const OBSERVATIONS: usize,
        const CHECKPOINTS: usize,
        const INTENTS: usize,
        const TASKS: usize,
        const RUN_QUEUE: usize,
        const MESSAGES: usize,
        const MEMORY_CELLS: usize,
        const NAMESPACE_ENTRIES: usize,
        const FAULTS: usize,
        const FAULT_HANDLERS: usize,
        const FAULT_POLICIES: usize,
        const WAITERS: usize,
        const AGENT_IMAGES: usize,
        const DRIVER_BINDINGS: usize,
        const DEVICE_EVENTS: usize,
        const DRIVER_COMMANDS: usize,
    >
    KernelCore<
        AGENTS,
        RESOURCES,
        CAPS,
        EVENTS,
        ACTIONS,
        OBSERVATIONS,
        CHECKPOINTS,
        INTENTS,
        TASKS,
        RUN_QUEUE,
        MESSAGES,
        MEMORY_CELLS,
        NAMESPACE_ENTRIES,
        FAULTS,
        FAULT_HANDLERS,
        FAULT_POLICIES,
        WAITERS,
        AGENT_IMAGES,
        DRIVER_BINDINGS,
        DEVICE_EVENTS,
        DRIVER_COMMANDS,
    >
{
    pub(crate) fn record_wait_signal_event(
        &mut self,
        kind: EventKind,
        agent: AgentId,
        capability: CapabilityId,
        resource: ResourceId,
        task: Option<TaskId>,
        waiter: Option<WaiterId>,
        signal: SignalKey,
        target_agent: Option<AgentId>,
    ) -> Result<Event, KernelError> {
        let intent = match task {
            Some(task) => Some(self.find_task(task)?.intent),
            None => None,
        };

        self.record(Event {
            sequence: 0,
            agent,
            kind,
            resource: Some(resource),
            capability: Some(capability),
            source_capability: None,
            intent,
            intent_kind: None,
            action: None,
            observation: None,
            message: None,
            memory_cell: None,
            namespace_entry: None,
            namespace_key: None,
            namespace_object: None,
            operation: None,
            operations: OperationSet::empty(),
            verification: VerificationRequirement::Optional,
            checkpoint: None,
            task,
            task_ticks: None,
            task_quantum: None,
            fault: None,
            fault_kind: None,
            fault_detail: None,
            fault_policy: None,
            fault_policy_action: None,
            waiter,
            signal: Some(signal),
            target_agent,
            driver_binding: None,
            device_event: None,
            device_event_kind: None,
            device_event_payload: None,
            driver_command: None,
            driver_command_kind: None,
            driver_command_payload: None,
            driver_command_result: None,
            agent_image: None,
            agent_image_kind: None,
            agent_image_digest: None,
            agent_image_abi_version: None,
            agent_image_entry_version: None,
        })
    }
}
